// BALANCE games: settings for each painting (see engines/balance.js for what each setting means).
export default {
  'take-time-to-bloom': {
    engine: 'balance', title: 'Take time to bloom', kicker: 'Take time to bloom', unit: 'bloom',
    how: 'The clock pulls you this way, then that way. Hold the left or right side of the screen to push back, and keep the flower in the calm zone so it can bloom.',
    center: [0.5, 0.6], span: 0.2, safe: 0.4, orb: '\u{1F33C}', color: '#ffb347',
    time: 40, push: 2.6, damp: 2.0, drift: [0.3, 0.7],
    // a pendulum: tick-tock pushes that swap sides every time and come faster as the flower opens
    gusts: { gap: [2.6, 1.5], dur: [1.0, 1.3], str: [1.5, 2.3], warn: 1.0, dirs: 'alternate' },
    gust: { e: '⏰', name: 'The clock', sound: 'tick', color: '#ffd9a0' },
    bloom: { at: [0.6, 0.34], type: 'ring', r: 0.1, n: 10, e: ['\u{1F338}', '\u{1F33A}'], size: 0.075, glow: 0.42 },
    veil: { mode: 'fade', color: '#151824', opacity: 0.5 },
    pitch: 392, chord: [261.6, 329.6, 392, 523.3],
    stages: ['A petal opens', 'Half in bloom', 'Almost in full bloom'], wobble: 'Pulled away!',
    win: { title: 'You bloomed', line: '“…when I took that time, and worked on myself, I truly flourished. It was like a flower blooming…” — Steven McCoy' },
    lose: { title: 'Take your time', line: '“You are a person. You deserve your time and attention as well.” — Steven McCoy' },
  },
  'hope-is-not-lost': {
    engine: 'balance', title: 'Hold the island', kicker: 'Hope is not lost', unit: 'hope',
    how: 'Storms push the floating island. Hold the left or right side of the screen to lean against them, keep it level, and let the green grow back.',
    center: [0.5, 0.53], span: 0.2, safe: 0.36, orb: '\u{1F3DD}️', color: '#7be08a',
    time: 42, push: 2.4, damp: 1.7, drift: [0.25, 0.6],
    // big, slow storms from either side, with long lulls between
    gusts: { gap: [3.8, 2.4], dur: [1.6, 2.2], str: [1.2, 1.9], warn: 1.3, dirs: 'random' },
    gust: { e: '⛈️', name: 'A storm', sound: 'thunder', color: '#cfd8e8' },
    bloom: { at: [0.5, 0.35], type: 'points', size: 0.065, glow: 0.55, e: ['\u{1F33F}', '\u{1F333}', '\u{1F331}', '\u{1F334}', '\u{1F33C}'],
      points: [[0.47, 0.37], [0.32, 0.31], [0.66, 0.31], [0.28, 0.36], [0.72, 0.33], [0.39, 0.4], [0.58, 0.4], [0.53, 0.31], [0.62, 0.36], [0.35, 0.36], [0.43, 0.32]] },
    veil: { mode: 'fade', color: '#3b4458', opacity: 0.6 },
    pitch: 294, chord: [293.7, 370, 440, 587.3],
    stages: ['Green is growing back', 'The island steadies', 'Hope in full view'], wobble: 'The island tips!',
    win: { title: 'Hope is not lost', line: '“You have to have a vision for hope in the future…” — Ricky Ruzicka' },
    lose: { title: 'Hold on to hope', line: '“…just because you lose something doesn’t mean that there’s nothing to be gained from it.” — Ricky Ruzicka' },
  },
  'the-bridge-of-perception': {
    engine: 'balance', title: 'Head above water', kicker: 'Head above water', unit: 'air',
    how: 'The creek rocks the boy back and forth. Hold the left or right side of the screen to swim against the current and keep his head above the water.',
    center: [0.5, 0.73], span: 0.2, safe: 0.4, orb: '\u{1FAE7}', color: '#9fe8ff',
    time: 38, push: 2.6, damp: 1.8, drift: [0.2, 0.4],
    // the current rocks you all the time; swells come on top and sometimes slosh straight back
    current: { amp: 0.9, period: 6 },
    gusts: { gap: [3.4, 2.2], dur: [1.2, 1.6], str: [1.3, 2.0], warn: 1.2, dirs: 'random', twin: 0.35 },
    gust: { e: '\u{1F30A}', name: 'A wave', sound: 'water', color: '#bff3ff' },
    bloom: { at: [0.5, 0.52], type: 'points', size: 0.06, glow: 0.45, e: ['✨'],
      points: [[0.3, 0.58], [0.7, 0.58], [0.28, 0.67], [0.72, 0.67], [0.38, 0.65], [0.62, 0.65], [0.3, 0.48], [0.7, 0.48]] },
    veil: { mode: 'rise', color: '#2c5a50', calm: 0.97, storm: 0.66, opacity: 0.7 },
    pitch: 220, chord: [220, 261.6, 329.6, 440],
    stages: ['Breathing easier', 'The water settles', 'Nearly to the bank'], wobble: 'Under the water!',
    win: { title: 'Head above water', line: '“I wonder what’s on the other side of this bridge.” — Bill McCann' },
    lose: { title: 'Look again', line: '“We can’t totally trust our own perceptions of the world.” — Bill McCann' },
  },
  'flow-state': {
    engine: 'balance', title: 'Keep the flow', kicker: 'Flow state', unit: 'flow',
    how: 'Too many ideas pull you every way. Hold the left or right side of the screen to steady the brush, and keep it in the calm zone so the colours keep flowing.',
    center: [0.5, 0.72], span: 0.2, safe: 0.38, orb: '\u{1F3A8}', color: '#ff9a3c',
    time: 40, push: 2.8, damp: 2.2, drift: [0.3, 0.6],
    // a swarm of quick little pulls, often one straight after another from the other side
    gusts: { gap: [1.9, 1.1], dur: [0.6, 0.9], str: [1.8, 2.6], warn: 0.8, dirs: 'random', twin: 0.4 },
    gust: { e: '\u{1F4A1}', name: 'An idea', sound: 'chime', color: '#fff2a8' },
    bloom: { at: [0.5, 0.44], type: 'ring', r: 0.18, n: 12, size: 0.06, glow: 0.7,
      e: ['\u{1F534}', '\u{1F7E0}', '\u{1F7E1}', '\u{1F7E2}', '\u{1F535}', '\u{1F7E3}'] },
    veil: { mode: 'fade', color: '#7a7a7a', opacity: 0.6 },
    pitch: 349, chord: [349.2, 440, 523.3, 784],
    stages: ['The colours are flowing', 'Unblurred', 'Pure flow'], wobble: 'Lost the flow!',
    win: { title: 'In the flow', line: '“I always have art flowing through me. I never have that block to create art.” — Raquel Alim' },
    lose: { title: 'Find the flow again', line: '“I think my issue is I have too many things in my head that I need to paint.” — Raquel Alim' },
  },
  'inner-peace-in-outer-chaos': {
    engine: 'balance', title: 'Carry the calm', kicker: 'Inner peace', unit: 'peace',
    how: 'The storm swirls all around you. Hold the left or right side of the screen to push back, and keep your calm in the middle. Peace is something you carry.',
    center: [0.51, 0.64], span: 0.2, safe: 0.36, orb: '\u{1F54A}️', color: '#b9a6ff',
    time: 42, push: 2.8, damp: 1.9, drift: [0.4, 1.3],
    // chaos that keeps building: restless all the time, pushes come harder and closer together
    gusts: { gap: [3.0, 1.4], dur: [1.0, 1.5], str: [1.3, 2.5], warn: 1.0, dirs: 'random', twin: 0.25 },
    gust: { e: '\u{1F32A}️', name: 'Chaos', sound: 'wind', color: '#ff8ad8' },
    bloom: { at: [0.52, 0.4], type: 'ring', r: 0.15, n: 10, size: 0.06, glow: 0.5, e: ['✨', '\u{1F31F}'] },
    veil: { mode: 'fade', color: '#120a22', opacity: 0.7 },
    pitch: 262, chord: [261.6, 349.2, 392, 523.3],
    stages: ['Breathe in', 'Breathe out', 'Peace within'], wobble: 'Swept up!',
    win: { title: 'Peace within', line: '“Peace is something I carry into the chaos. It is found within…” — Morten Bonde' },
    lose: { title: 'Breathe and return', line: '“…peace is not something that arrives when the chaos stops.” — Morten Bonde' },
  },
};
