// CONNECT games: settings for each painting (see engines/connect.js for what each setting means).
export default {
  // the family tree: from the people at its feet, down into the roots, up the trunk and out along the branches
  'roots-of-kinship': {
    engine: 'connect', title: 'Grow the family tree', kicker: 'Grow the family tree', unit: 'linked',
    how: 'A spark climbs the tree from root to branch. Tap anywhere as the ring closes on the next branch to link your family.',
    nodes: [
      { u: 0.5, v: 0.76, name: 'The roots' },
      { u: 0.5, v: 0.63, name: 'The trunk' },
      { u: 0.5, v: 0.51, name: 'Where it splits' },
      { u: 0.32, v: 0.5, name: 'A sister branch' },
      { u: 0.68, v: 0.5, name: 'The other sister' },
      { u: 0.27, v: 0.38, name: 'A swirl of leaves' },
      { u: 0.73, v: 0.39, name: 'A blue flower' },
      { u: 0.39, v: 0.33, name: 'New leaves' },
      { u: 0.61, v: 0.33, name: 'A young shoot' },
      { u: 0.32, v: 0.27, name: 'High on the left' },
      { u: 0.67, v: 0.27, name: 'High on the right' },
      { u: 0.5, v: 0.25, name: 'The crown' },
    ],
    travel: [2.5, 1.35], window: [0.32, 0.2], rest: 0.7, warmth: { drain: 1.0, miss: 14, link: 5 },
    scale: 'major', color: '#ffc861', ringColor: '#ff9a3c', hum: 'triangle',
    together: 'The whole tree is glowing. Every generation, together.',
    win: { title: 'The tree is whole', line: '“You get through it — life is on the other side. It’s different, but you can live a fulfilled life.” — April & Melissa' },
    lose: { title: 'Tend the roots again', line: '“We’re now, as a family, cohesively dealing with the same genetic disease. So you get through it.” — April & Melissa' },
  },
  // the musical town: player to player along the shore, over the bridge, through the band and up the hill to the sun
  'harmonious-gathering': {
    engine: 'connect', title: 'Bring the band together', kicker: 'Bring the band together', unit: 'players',
    how: 'A note travels from player to player across the town. Tap anywhere as the ring closes to bring each one into the song.',
    nodes: [
      { u: 0.26, v: 0.72, name: 'The accordion player' },
      { u: 0.35, v: 0.75, name: 'Across the bridge' },
      { u: 0.47, v: 0.57, name: 'The horn player in red' },
      { u: 0.59, v: 0.75, name: 'The flute player' },
      { u: 0.73, v: 0.75, name: 'The guitarist' },
      { u: 0.73, v: 0.58, name: 'The yellow house' },
      { u: 0.63, v: 0.56, name: 'The red house' },
      { u: 0.62, v: 0.42, name: 'The listener on the rock' },
      { u: 0.6, v: 0.31, name: 'The drum' },
      { u: 0.49, v: 0.33, name: 'The curling horns' },
      { u: 0.42, v: 0.39, name: 'The pink house' },
      { u: 0.3, v: 0.3, name: 'The tree on the hill' },
    ],
    travel: [2.2, 1.2], window: [0.3, 0.19], rest: 0.6, warmth: { drain: 1.1, miss: 14, link: 5 },
    scale: 'blues', color: '#ffb347', ringColor: '#ff6a3d', hum: 'sawtooth', button: 'Play',
    together: 'The whole town is playing together.',
    win: { title: 'The whole town is playing', line: '“It’s just such a great feeling to meet someone at a show… That interaction is incredible to me.” — Will Hollimon' },
    lose: { title: 'Tune up and try again', line: '“People really care about what I do as a musician, and that feels really good.” — Will Hollimon' },
  },
  // the family: hand to hand through the crowd, from the figures behind to the little ones in front
  'embracing-unity': {
    engine: 'connect', title: 'Hold hands', kicker: 'Hold hands', unit: 'together',
    how: 'Love passes from hand to hand through the family. Tap anywhere as the ring closes on the next person to join hands.',
    nodes: [
      { u: 0.4, v: 0.27, name: 'Someone far back' },
      { u: 0.47, v: 0.29, name: 'Walking beside him' },
      { u: 0.41, v: 0.47, name: 'The woman in red' },
      { u: 0.27, v: 0.43, name: 'Arms open wide' },
      { u: 0.29, v: 0.67, name: 'Sister in flowers' },
      { u: 0.4, v: 0.75, name: 'The little one in red' },
      { u: 0.53, v: 0.47, name: 'Dad' },
      { u: 0.645, v: 0.73, name: 'Holding Dad\u2019s hand' },
      { u: 0.735, v: 0.71, name: 'Sister in blue' },
    ],
    travel: [2.7, 1.5], window: [0.32, 0.2], rest: 0.75, warmth: { drain: 1.05, miss: 13, link: 5 },
    scale: 'penta', color: '#ff8fb8', ringColor: '#ff4f7a', hum: 'sine', button: 'Join hands',
    together: 'Everyone is holding hands. The whole family, together.',
    win: { title: 'The whole family, together', line: '“They’re always there when I need them the most.” — Shardasia Hadley' },
    lose: { title: 'Reach out again', line: '“I’m grateful and appreciative of the support my family gives me every day.” — Shardasia Hadley' },
  },
};
