// ECHO games: settings for each painting (see engines/echo.js for what each setting means).
// Pads are listed LEFT TO RIGHT; the big buttons along the bottom follow the same order.
export default {
  'reflections-of-sisterhood': {
    engine: 'echo', title: 'Mirror me, sister', kicker: 'Mirror me, sister', unit: 'notes',
    how: 'Your sister goes first. Listen, then copy her: tap the sisters and their reflections, or the four buttons, in the same order.',
    pads: [
      { u: 0.33, v: 0.32, name: 'April', btn: 'April', color: '#ffd25a', note: 392, sound: 'voice', vowel: 'a', pair: 1 },
      { u: 0.32, v: 0.68, name: 'April’s reflection', btn: 'Her ripple', color: '#7fd0ff', note: 196, sound: 'drop', pair: 0 },
      { u: 0.59, v: 0.30, name: 'Melissa', btn: 'Melissa', color: '#ff7ab8', note: 523.3, sound: 'voice', vowel: 'e', pair: 3 },
      { u: 0.61, v: 0.68, name: 'Melissa’s reflection', btn: 'Her ripple', color: '#4fa8ff', note: 261.6, sound: 'drop', pair: 2 },
    ],
    padSize: 0.1, start: 2, target: 7, maxMiss: 3, gap: 0.62, pattern: 'random', reward: 'splash',
    listen: ['Your sister goes first.', 'Watch your sister.', 'Her turn.', 'Listen to her.', 'Your sister again.', 'One more from your sister.'],
    turn: 'Now mirror her.', praise: ['Just like her.', 'Mirror perfect.', 'Splash!', 'Sisters in step.', 'Feet in the water.'],
    missTitle: 'Ripple!',
    win: { title: 'Two of a kind', line: '“It’s a little house and their backyard is water. So, we would sit back there, kick our feet in.” — April & Melissa' },
    lose: { title: 'Kick your feet in again', line: '“That’s where we went every summer.” — April & Melissa' },
  },
  'the-scope-of-communication': {
    engine: 'echo', title: 'Say it back', kicker: 'Say it back', unit: 'words',
    how: 'Two people are talking. Listen to the conversation, then say it back: tap think, speak, hear and feel, or the four buttons, in the same order.',
    pads: [
      { u: 0.32, v: 0.36, name: 'Think', btn: 'Think', color: '#3fd0b0', note: 196, sound: 'voice', vowel: 'o' },
      { u: 0.41, v: 0.52, name: 'Speak', btn: 'Speak', color: '#ffd25a', note: 293.7, sound: 'voice', vowel: 'a' },
      { u: 0.58, v: 0.52, name: 'Hear', btn: 'Hear', color: '#ff5a3a', note: 392, sound: 'voice', vowel: 'i' },
      { u: 0.67, v: 0.36, name: 'Feel', btn: 'Feel', color: '#ff9a2a', note: 523.3, sound: 'voice', vowel: 'u' },
    ],
    padSize: 0.1, start: 2, target: 7, maxMiss: 3, gap: 0.66, pattern: 'alternate', reward: 'reply',
    listen: ['They talk first.', 'Listen to them.', 'A longer talk.', 'Hear them out.', 'Listen closely.', 'The last word.'],
    turn: 'Now say it back.', praise: ['Understood.', 'Well said.', 'You listened.', 'Heard and felt.', 'Connected.'],
    missTitle: 'Crossed wires',
    win: { title: 'You understood', line: '“The goal of the project is to enlighten and broaden the scope of communication…” — Marcus Roberts' },
    lose: { title: 'Lost in translation', line: 'Listen, then answer. Every conversation takes practice.' },
  },
  'the-visions-that-we-share': {
    engine: 'echo', title: 'Share the vision', kicker: 'Share the vision', unit: 'glimpses',
    how: 'The eye shows you what it sees. Share it back: tap the corner, the lid, the pupil and the lashes, or the four buttons, in the same order.',
    pads: [
      { u: 0.31, v: 0.50, name: 'The corner', btn: 'Corner', color: '#ffb38a', note: 329.6, sound: 'glass' },
      { u: 0.43, v: 0.62, name: 'The lid', btn: 'Lid', color: '#5aa0e8', note: 246.9, sound: 'bell' },
      { u: 0.52, v: 0.44, name: 'The pupil', btn: 'Pupil', color: '#ffe08a', note: 440, sound: 'glass' },
      { u: 0.67, v: 0.33, name: 'The lashes', btn: 'Lashes', color: '#9ad0ff', note: 587.3, sound: 'glass' },
    ],
    padSize: 0.1, start: 2, target: 7, maxMiss: 3, gap: 0.6, pattern: 'random', reward: 'shimmer',
    listen: ['Look with me.', 'See what I see.', 'Another glimpse.', 'Look closer.', 'Keep watching.', 'One last vision.'],
    turn: 'Now share it back.', praise: ['Shared.', 'You see it.', 'Clear as light.', 'Together.', 'One shared story.'],
    missTitle: 'Blurred',
    win: { title: 'A vision shared', line: '“Together we can change the world’s view of sight loss, one word, one poem, one shared story at a time.” — Dave Steele' },
    lose: { title: 'Look again', line: '“…one word, one poem, one shared story at a time.” — Dave Steele' },
  },
  'the-harmony-of-vision': {
    engine: 'echo', title: 'Sing it back', kicker: 'Sing it back', unit: 'notes',
    how: 'The painting plays a tune. Sing it back: tap the wave, drum, notes, score and sun, or the five buttons, in the same order.',
    pads: [
      { u: 0.33, v: 0.60, name: 'The wave', btn: 'Wave', color: '#ffd25a', note: 261.6, sound: 'pluck' },
      { u: 0.37, v: 0.34, name: 'The drum', btn: 'Drum', color: '#ff3b3b', note: 293.7, sound: 'drum' },
      { u: 0.50, v: 0.68, name: 'The notes', btn: 'Notes', color: '#4fb8ff', note: 329.6, sound: 'bell' },
      { u: 0.56, v: 0.52, name: 'The score', btn: 'Score', color: '#ffffff', note: 392, sound: 'voice', vowel: 'a' },
      { u: 0.69, v: 0.36, name: 'The sun', btn: 'Sun', color: '#ffb02e', note: 440, sound: 'glass' },
    ],
    padSize: 0.09, start: 3, target: 8, maxMiss: 3, gap: 0.5, pattern: 'melodic', reward: 'chord',
    listen: ['Listen to the tune.', 'A little longer.', 'Hear the melody.', 'The band plays on.', 'Almost a song.', 'The big finish.'],
    turn: 'Sing it back.', praise: ['In tune.', 'Bravo.', 'Sweet harmony.', 'Encore!', 'What a voice.', 'Perfect pitch.'],
    missTitle: 'Off key',
    win: { title: 'Perfect harmony', line: '“I feel like these students have incredible vision.” — Deb Beyer, AMB vocal instructor' },
    lose: { title: 'Practice makes music', line: '“They tell us, the teachers… this is how I want to play or sing better.” — Deb Beyer, AMB vocal instructor' },
  },
};
