// POP games: settings for each painting (see engines/pop.js for what each setting means).
export default {
  'reasons-for-a-cure': {
    engine: 'pop', title: 'Find your reasons', kicker: 'Find your reasons', unit: 'reasons',
    how: 'Faces and moments light up on the wall of photos. Tap each one before it fades. Let the menus and cars go.',
    spots: [{ u: 0.32, v: 0.28 }, { u: 0.46, v: 0.3 }, { u: 0.6, v: 0.27 }, { u: 0.69, v: 0.34 }, { u: 0.37, v: 0.42 },
      { u: 0.63, v: 0.42 }, { u: 0.31, v: 0.56 }, { u: 0.69, v: 0.55 }, { u: 0.31, v: 0.73 }, { u: 0.69, v: 0.73 }],
    good: [{ e: '\u{1F469}', name: 'a loved one' }, { e: '\u{1F476}', name: 'a baby’s smile' }, { e: '\u{1F468}‍\u{1F469}‍\u{1F467}', name: 'family' },
      { e: '\u{1F475}', name: 'grandma' }, { e: '\u{1F305}', name: 'a sunrise' }, { e: '\u{1F490}', name: 'flowers' }, { e: '\u{1F30A}', name: 'the sea' }],
    bad: [{ e: '\u{1F4CB}', name: 'a menu' }, { e: '\u{1F697}', name: 'a car' }], badChance: 0.18,
    badHit: 'Just a menu', badLine: 'The faces matter more. Minus 2 seconds.',
    goal: 28, time: 70, window: [2.6, 1.4], every: [1.7, 0.85], maxOn: [1, 2], size: 0.11,
    sound: 'photo', scale: 'major', color: '#ffd9a0', comboWord: 'Memories',
    win: { title: 'So many reasons', line: '“…we can’t see a loved one’s face. And that is so much more meaningful, I think, than the reading or driving.” — Rusty Perez' },
    lose: { title: 'Look again', line: '“Maybe the reason to take a cure is for those deeply emotional things that I miss out on.” — Rusty Perez' },
  },
  'seeing-the-world-together': {
    engine: 'pop', title: 'See it together', kicker: 'See it together', unit: 'wonders',
    how: 'Wonders glimmer across the sky, the city and the lake. Tap each one so you both can see it. Leave the grey clouds be.',
    spots: [{ u: 0.42, v: 0.26 }, { u: 0.62, v: 0.3 }, { u: 0.32, v: 0.3 }, { u: 0.46, v: 0.42 }, { u: 0.69, v: 0.45 },
      { u: 0.57, v: 0.53 }, { u: 0.62, v: 0.63 }, { u: 0.52, v: 0.75 }, { u: 0.68, v: 0.69 }, { u: 0.45, v: 0.86 }],
    good: [{ e: '\u{1FA90}', name: 'a ringed planet' }, { e: '\u{1F305}', name: 'the sunset' }, { e: '\u{1F98B}', name: 'a butterfly' },
      { e: '\u{1F338}', name: 'a flower' }, { e: '\u{1F426}', name: 'a bird' }, { e: '✨', name: 'starlight' }, { e: '\u{1F308}', name: 'a rainbow' }, { e: '\u{1F6F8}', name: 'a sky ship' }],
    bad: [{ e: '☁️', name: 'a grey cloud' }], badChance: 0.14,
    badHit: 'Just a cloud', badLine: 'Wait for the wonders. Minus 2 seconds.',
    goal: 26, time: 70, window: [2.8, 1.5], every: [1.8, 0.95], maxOn: [1, 2], size: 0.11,
    sound: 'shimmer', scale: 'penta', color: '#ffb36b', comboWord: 'Together',
    win: { title: 'You saw it together', line: '“We both get to see the world together and I am grateful for it.” — Ricky Ruzicka' },
    lose: { title: 'Look again, together', line: '“She is my eyes and I help her out in the ways that I do.” — Ricky Ruzicka' },
  },
  'haute-couture-dreams': {
    engine: 'pop', title: 'Style rush', kicker: 'Style rush', unit: 'looks',
    how: 'Dream pieces flash all over the collage, sometimes two or three at once. Tap every look you love before it slips away.',
    spots: [{ u: 0.32, v: 0.5 }, { u: 0.31, v: 0.33 }, { u: 0.69, v: 0.43 }, { u: 0.68, v: 0.62 }, { u: 0.68, v: 0.28 },
      { u: 0.31, v: 0.7 }, { u: 0.69, v: 0.79 }, { u: 0.32, v: 0.86 }, { u: 0.86, v: 0.75 }, { u: 0.14, v: 0.4 }],
    good: [{ e: '\u{1F457}', name: 'a dress' }, { e: '\u{1F460}', name: 'heels' }, { e: '\u{1F45C}', name: 'a bag' }, { e: '\u{1F9E5}', name: 'a coat' },
      { e: '\u{1F452}', name: 'a hat' }, { e: '\u{1F576}️', name: 'sunglasses' }, { e: '\u{1F45A}', name: 'a blouse' }, { e: '\u{1F9E3}', name: 'a scarf' }],
    goal: 40, time: 65, window: [2.0, 1.1], every: [1.2, 0.55], maxOn: [1, 3], size: 0.1,
    sound: 'snap', scale: 'major', color: '#ffe23a', comboWord: 'On trend',
    win: { title: 'Your style, real', line: '“I like trying out certain colors to see how they look on me.” — Shardasia Hadley' },
    lose: { title: 'Try another look', line: '“I like finding new and different styles of clothing, whether it be chic or kind of baggy.” — Shardasia Hadley' },
  },
  'the-power-within': {
    engine: 'pop', title: 'Answer the call', kicker: 'Answer the call', unit: 'helped',
    how: 'People call out from the windows of the city. Tap each one to answer, fast. Ignore the doubters.',
    spots: [{ u: 0.32, v: 0.4 }, { u: 0.31, v: 0.57 }, { u: 0.31, v: 0.76 }, { u: 0.5, v: 0.86 }, { u: 0.69, v: 0.78 },
      { u: 0.68, v: 0.57 }, { u: 0.68, v: 0.42 }, { u: 0.69, v: 0.28 }, { u: 0.08, v: 0.4 }, { u: 0.88, v: 0.36 }],
    good: [{ e: '\u{1F64B}', name: 'a curious kid' }, { e: '\u{1F64B}‍♂️', name: 'someone with a question' }, { e: '\u{1F475}', name: 'a neighbour' },
      { e: '\u{1F9D2}', name: 'a child' }, { e: '\u{1F408}', name: 'a lost cat' }, { e: '\u{1F44B}', name: 'a friend waving' }],
    bad: [{ e: '\u{1F44E}', name: 'a doubter' }], badChance: 0.22,
    badHit: 'A doubter', badLine: 'Don’t let it stop you. Minus 2 seconds.',
    goal: 30, time: 65, window: [2.2, 1.0], every: [1.5, 0.7], maxOn: [1, 2], size: 0.1,
    sound: 'hero', scale: 'major', color: '#ffd23a', comboWord: 'Super',
    win: { title: 'Superpower on', line: '“Blindness is resilience, a superpower.” — Acabella, Academy of Music for the Blind' },
    lose: { title: 'Rise again', line: '“I don’t want to let my blindness stop me from experiencing things.” — Acabella, Academy of Music for the Blind' },
  },
};
