// REVEAL games: settings for each painting (see engines/reveal.js for what each setting means).
export default {
  'find-your-village': {
    engine: 'reveal', title: 'Find your village', kicker: 'Find your village', unit: 'found', coverName: 'dark',
    how: 'You think you are alone in the dark. Drag your finger to wipe it away and find your village. The pulse gets faster as you get close.',
    fog: { colors: ['#060814', '#141a36', '#2a1a2e'], stars: true, opacity: 0.97 },
    targets: [
      { u: 0.19, v: 0.08, r: 0.05, e: '\u{1F319}', name: 'The crescent moon' },
      { u: 0.2, v: 0.25, r: 0.065, e: '\u{1F3F0}', name: 'The castle towers' },
      { u: 0.3, v: 0.45, r: 0.06, e: '\u{1F52E}', name: 'The glowing globe' },
      { u: 0.45, v: 0.52, r: 0.055, e: '\u{1F333}', name: 'The white tree' },
      { u: 0.63, v: 0.38, r: 0.06, e: '\u{1F3D8}️', name: 'The golden village' },
      { u: 0.16, v: 0.64, r: 0.06, e: '\u{1F642}', name: 'The face that holds it all' },
      { u: 0.92, v: 0.48, r: 0.05, e: '\u{1F426}', name: 'A bird flying home' },
    ],
    lights: true, lift: 0.3, brush: 0.075, time: 90, color: '#ffc658', alertKind: 'black',
    voice: { type: 'triangle', base: 330 },
    win: { title: 'You found your village', line: '“You think that you’re alone, but eventually, like a magnet, you just start attracting everyone you’re supposed to.” — Steven McCoy' },
    lose: { title: 'Your village is out there', line: '“The beautiful thing about being authentic, you find your village.” — Steven McCoy' },
  },
  'the-only-light-well-see': {
    engine: 'reveal', title: 'Follow the moonlight', kicker: 'Follow the moonlight', unit: 'found', coverName: 'night',
    how: 'The night is deep, but the moon still shines. Drag your finger to wipe away the dark and find what its light touches. Listen: the pulse quickens as you get close.',
    fog: { colors: ['#020306', '#070b14', '#03050a'], stars: true, opacity: 0.985 },
    beacons: [{ u: 0.63, v: 0.26, size: 0.2, color: '#fff3cf', opacity: 0.85 }],
    targets: [
      { u: 0.63, v: 0.455, r: 0.05, e: '✨', name: 'The silver path on the water' },
      { u: 0.62, v: 0.62, r: 0.055, e: '\u{1F315}', name: 'The moon in the lake' },
      { u: 0.2, v: 0.24, r: 0.07, e: '\u{1F332}', name: 'The tall trees' },
      { u: 0.42, v: 0.52, r: 0.055, e: '\u{1F3DE}️', name: 'The point of land' },
      { u: 0.8, v: 0.42, r: 0.055, e: '⛰️', name: 'The far hills' },
      { u: 0.24, v: 0.66, r: 0.06, e: '\u{1F30A}', name: 'The trees reflected' },
    ],
    brush: 0.065, time: 80, color: '#dfe9ff', alertKind: 'blue',
    voice: { type: 'sine', base: 280 },
    win: { title: 'You followed the light', line: '“In the darkest of nights, we learn to find our own light, and to become that light for others.” — Dave Steele' },
    lose: { title: 'Keep the light in sight', line: '“In the darkest of nights, we learn to find our own light…” — Dave Steele' },
  },
  'a-new-day': {
    engine: 'reveal', title: 'Bring up the sun', kicker: 'Bring up the sun', unit: 'pieces of glass',
    coverName: 'night',
    how: 'It is a down moment, still night. Drag your finger to wipe it away and find each piece of the window. Every piece you find brings the sun up.',
    fog: { colors: ['#0a1030', '#1c1f5a', '#2b1846'], stars: false, opacity: 0.99, grain: '#8fb4ff' },
    sun: { u: 0.22, v: 0.56, size: 0.36, color: '#ffa53c', rise: 0.14 },
    targets: [
      { u: 0.21, v: 0.55, r: 0.06, e: '\u{1F305}', name: 'The sun on the sea' },
      { u: 0.33, v: 0.12, r: 0.06, e: '\u{1FA9F}', name: 'The top of the arch' },
      { u: 0.35, v: 0.42, r: 0.055, e: '\u{1F334}', name: 'The tall slender trees' },
      { u: 0.48, v: 0.67, r: 0.055, e: '\u{1F30A}', name: 'The calm ocean' },
      { u: 0.79, v: 0.47, r: 0.065, e: '\u{1F535}', name: 'The round blue window' },
      { u: 0.38, v: 0.8, r: 0.06, e: '\u{1FAA8}', name: 'The path of stones' },
    ],
    lift: 0.3, brush: 0.075, time: 85, color: '#ffb04a', alertKind: 'red',
    voice: { type: 'triangle', base: 260 },
    win: { title: 'A new day', line: '“I have my down moments, and that’s okay. Tomorrow is a new day.” — Raquel Alim' },
    lose: { title: 'Tomorrow is a new day', line: '“I get back out there and do whatever I can.” — Raquel Alim' },
  },
  'the-dark-uncertainty': {
    engine: 'reveal', title: 'Face the unknown', kicker: 'Face the unknown', unit: 'found', coverName: 'dark',
    how: 'People fear what they don’t know. Drag your finger through the dark bus and get to know what is really there. The pulse speeds up as you get close.',
    fog: { colors: ['#0b0503', '#1f0a05', '#120604'], stars: false, opacity: 0.975, grain: '#ff7a3a' },
    targets: [
      { u: 0.27, v: 0.28, r: 0.06, e: '\u{1F464}', name: 'The musician’s face' },
      { u: 0.37, v: 0.6, r: 0.06, e: '\u{1F3BA}', name: 'The trumpet' },
      { u: 0.46, v: 0.79, r: 0.055, e: '\u{1F3B5}', name: 'The trumpet’s bell' },
      { u: 0.52, v: 0.3, r: 0.06, e: '\u{1FA9F}', name: 'The bus window' },
      { u: 0.73, v: 0.33, r: 0.07, e: '\u{1F306}', name: 'The world passing by' },
      { u: 0.07, v: 0.14, r: 0.05, e: '\u{1F68C}', name: 'The bus lights' },
    ],
    brush: 0.075, time: 80, color: '#ff8a3a', alertKind: 'red',
    voice: { type: 'square', base: 233 },
    win: { title: 'Nothing to fear', line: '“What it’s really about is that people fear what they don’t know.” — Bill McCann' },
    lose: { title: 'Still in the dark', line: '“People fear what they don’t know.” — Bill McCann' },
  },
  'the-gray-zone': {
    engine: 'reveal', title: 'Name the gray zone', kicker: 'Name the gray zone', unit: 'named', coverName: 'fog',
    how: 'The fog keeps drifting back. Drag your finger to clear it and name each part of the glass cube before it hides again. The pulse quickens as you get close.',
    fog: { colors: ['#9a9ea6', '#c4c7cc', '#7d828a'], stars: false, opacity: 0.95, grain: '#ffffff' },
    targets: [
      { u: 0.24, v: 0.33, r: 0.055, e: '◻️', name: 'The cube’s top edge' },
      { u: 0.77, v: 0.33, r: 0.055, e: '\u{1F4D0}', name: 'The far corner' },
      { u: 0.47, v: 0.52, r: 0.07, e: '☁️', name: 'The cloud inside' },
      { u: 0.58, v: 0.82, r: 0.055, e: '\u{1F4A0}', name: 'The front corner' },
      { u: 0.86, v: 0.78, r: 0.06, e: '\u{1F311}', name: 'The shadow on the floor' },
    ],
    creep: 0.05, brush: 0.08, time: 80, color: '#ffffff', alertKind: 'black', ambient: 'wind',
    voice: { type: 'sine', base: 300 },
    win: { title: 'Named, and free', line: '“Naming that in-between space, instead of hiding it, is what finally set me free.” — Morten Bonde' },
    lose: { title: 'Still in the gray zone', line: '“For a long time I lived in a gray zone — no longer fully sighted, not yet identifying as blind.” — Morten Bonde' },
  },
};
