// RHYTHM games: settings for each painting (see engines/rhythm.js for what each setting means).
// Bars: 16 steps per bar (sixteenths), '.' = rest, a letter = that spot sounds; lower case = soft (up-strum / ghost).
export default {
  // Will at his drum kit: a rock beat that builds into fills.
  'rhythm-of-life': {
    engine: 'rhythm', title: 'Sit in on drums', kicker: 'Sit in on drums', bpm: 104,
    how: 'Will plays a beat, then it is your turn. Tap anywhere as each ring closes on a drum. Kick is low, snare cracks, toms boom, the cymbal crashes.',
    voice: 'drums', groove: 'hats', color: '#ff9a3c', size: 0.085, pass: 0.6, cue: 1320,
    spots: {
      K: { u: 0.505, v: 0.765, name: 'kick drum', e: '\u{1F941}', s: 'kick' },
      S: { u: 0.505, v: 0.655, name: 'snare', e: '\u{1F941}', s: 'snare' },
      T: { u: 0.315, v: 0.66, name: 'high tom', e: '\u{1F941}', s: 'tom1' },
      F: { u: 0.69, v: 0.66, name: 'floor tom', e: '\u{1F941}', s: 'tom2' },
      C: { u: 0.615, v: 0.54, name: 'cymbal', e: '\u{1F4C0}', s: 'crash' },
    },
    bars: [
      'K.......S.......',
      'K...S...K...S...',
      'K...S...K.K.S...',
      'K...S...K...S.S.',
      'C...S...K.K.S...',
      'K...S.T.K...S.F.',
      'K.K.S...K.K.S.T.',
      'C...S.K...K.S...',
      'K.T.S.F.K...S.S.',
      'T.T.S.S.F.F.K...',
      'C.K.S.K...K.S.T.',
      'K.T.S.F.T.F.C...',
    ],
    streakLine: 'Will would be proud.',
    win: { title: 'You kept the beat', line: '“It’s the best feeling in the world, whenever I sit down at a drumkit.” — Will Hollimon' },
    lose: { title: 'Count it in again', line: '“Early in life, I realized music is my main interest and passion.” — Will Hollimon' },
  },

  // Rusty's guitar: slow strummed chords, down and up.
  'reaching-past-blindness': {
    engine: 'rhythm', title: 'Strum with Rusty', kicker: 'Strum with Rusty', bpm: 84,
    how: 'Rusty strums a pattern, then you strum it back. Tap anywhere as each ring closes on the guitar. Each chord rings from its place on the strings.',
    voice: 'strum', groove: 'shaker', color: '#7fdcff', size: 0.085, pass: 0.6, cue: 1175,
    spots: {
      E: { u: 0.40, v: 0.64, name: 'E minor', e: '\u{1F3B8}', notes: [82.4, 123.5, 164.8, 196, 246.9, 329.6] },
      G: { u: 0.525, v: 0.545, name: 'G', e: '\u{1F3B5}', notes: [98, 123.5, 146.8, 196, 246.9, 392] },
      C: { u: 0.62, v: 0.48, name: 'C', e: '\u{1F3B5}', notes: [130.8, 164.8, 196, 261.6, 329.6] },
      D: { u: 0.715, v: 0.415, name: 'D', e: '\u{1F3B6}', notes: [146.8, 220, 293.7, 370] },
    },
    bars: [
      'E.......E.......',
      'E...E...G...G...',
      'C...C...D...D...',
      'E...E.e.G...G.g.',
      'C...C.c.D...D.d.',
      'E.e.E.e.G...G.g.',
      'C...c.C.D.d...D.',
      'E.e...e.G.g...g.',
      'C.c.C.c.D.d.D.d.',
      'G.g.C.c.D.d.E...',
    ],
    streakLine: 'Music reaches past the blindness.',
    win: { title: 'You reached past it', line: '“I call music a constant companion… I think it’s also helped me reach past the blindness.” — Rusty Perez' },
    lose: { title: 'Pick it up again', line: '“Maybe it’s helped others reach past the blindness… and connect with me on a personal level.” — Rusty Perez' },
  },

  // Alayna's cane tapping the street: the domes and painted notes sing back.
  'music-on-the-streets': {
    engine: 'rhythm', title: 'Cane on the crosswalk', kicker: 'Cane on the crosswalk', bpm: 96,
    how: 'Your cane taps a tune on the street, then you tap it back. Tap anywhere as each ring closes on a painted note. Low notes are on the left, high on the right.',
    voice: 'cane', groove: 'steps', color: '#ff7ab8', size: 0.085, pass: 0.6, cue: 1047,
    spots: {
      A: { u: 0.345, v: 0.655, name: 'low clef', e: '\u{1F3BC}', f: 261.6 },
      B: { u: 0.45, v: 0.45, name: 'white note', e: '\u{1F3B5}', f: 329.6 },
      C: { u: 0.555, v: 0.56, name: 'clef', e: '\u{1F3BC}', f: 392 },
      D: { u: 0.665, v: 0.42, name: 'orange swirl', e: '\u{1F3B6}', f: 440 },
      E: { u: 0.70, v: 0.62, name: 'high note', e: '\u{1F3B5}', f: 523.3 },
    },
    bars: [
      'A.......C.......',
      'A...C...A...C...',
      'A...B...C...D...',
      'A...C...E...C...',
      'A.A.C...D.D.C...',
      'B...C.D...C.B...',
      'A.B.C...C.D.E...',
      'E...D.C...B.A...',
      'A.C.E.C.A...E...',
      'C...C.D.E.D.C...',
      'E.D.C.B.A...A...',
    ],
    streakLine: 'The street is singing.',
    win: { title: 'The street sang back', line: '“Some of them sound like music and it’s the coolest thing ever.” — Alayna Lopez' },
    lose: { title: 'Cross again', line: '“I love going over all the different textures and the domes when you cross the street.” — Alayna Lopez' },
  },

  // Craig's drive: telephone poles whoosh past the window, near on the left, far down the road on the right.
  'telephone-poles': {
    engine: 'rhythm', title: 'Poles going by', kicker: 'Poles going by', bpm: 92,
    how: 'Ride down Craig’s highway. Listen to the poles whoosh by, then tap anywhere as each ring closes on one. The road keeps the beat.',
    voice: 'pole', groove: 'road', color: '#ffb347', size: 0.08, pass: 0.6, cue: 784,
    spots: {
      A: { u: 0.38, v: 0.37, name: 'wires overhead', e: '\u{1F4A8}', f: 196 },
      B: { u: 0.595, v: 0.38, name: 'bent pole', e: '\u{1F4A8}', f: 247 },
      C: { u: 0.645, v: 0.48, name: 'pole', e: '\u{1F4A8}', f: 294 },
      D: { u: 0.70, v: 0.585, name: 'far pole', e: '\u{1F4A8}', f: 330 },
    },
    bars: [
      'A.......B.......',
      'A...B...C...D...',
      'D...C...B...A...',
      'A...B...C.D.A...',
      'A.B...C.D...A...',
      'D...C.B...A.B...',
      'A.A.B...C.C.D...',
      'A...B.C...D.C...',
      'A.B.C.D.A...D...',
      'D.C.B.A.B.C.D...',
    ],
    streakLine: 'Straight as an arrow.',
    win: { title: 'Straight down the road', line: '“He said, those things are straight as an arrow.” — Craig Ellis' },
    lose: { title: 'Keep driving', line: '“All the telephone poles looked like they went straight up and then bent over at the top.” — Craig Ellis' },
  },

  // Marcus Roberts' Rhapsody: swung blue piano notes over a walking bass.
  'rhapsody-in-blue': {
    engine: 'rhythm', title: 'Swing the Rhapsody', kicker: 'Swing the Rhapsody', bpm: 120, swing: 0.16,
    how: 'The piano plays a swinging phrase, then you play it back. Tap anywhere as each ring closes on a note. Low notes sit down low, high notes up top.',
    voice: 'piano', groove: 'ride', color: '#ffd84a', ring: '#ffffff', size: 0.08, pass: 0.6, cue: 1397, gliss: true,
    spots: {
      L: { u: 0.48, v: 0.735, name: 'low note', e: '\u{1F3B9}', f: 233.1, under: 116.5 },
      Q: { u: 0.33, v: 0.60, name: 'swirl note', e: '\u{1F3B5}', f: 311.1 },
      W: { u: 0.585, v: 0.32, name: 'black note', e: '\u{1F3B5}', f: 415.3 },
      E: { u: 0.335, v: 0.30, name: 'high note', e: '\u{1F3B6}', f: 466.2 },
      R: { u: 0.67, v: 0.385, name: 'blue note', e: '\u{1F3B5}', f: 349.2 },
    },
    bars: [
      'L.......W.......',
      'L...Q...W...E...',
      'E...R...W...L...',
      'L.Q.W...R...W...',
      'W...R.E...R.W...',
      'L.L.Q...W.R.E...',
      'E.R.W.Q.L.......',
      'Q...W.R...E.R...',
      'L.Q.W.R.E.R.W...',
      'W...R.E...W.L...',
      'L.Q.W.R.E.R.W.Q.',
      'E.R.W.Q.L...L...',
    ],
    streakLine: 'That is jazz.',
    win: { title: 'You swung it', line: '“I want to use classical musicians and jazz musicians for this record.” — Marcus Roberts' },
    lose: { title: 'Take it again', line: '“He asked me, what do you want to do? We need something different.” — Marcus Roberts' },
  },
};
