// RUNNER games: settings for each painting (see engines/runner.js for what each setting means).
// Road positions are u,v (0..1 from the painting's top-left): vp = where the road vanishes, near = [centre u, v, width].
export default {
  'reliroo': {
    engine: 'runner', title: 'Lead the way, Reliroo', kicker: 'Lead the way', unit: 'steps', goal: 1000,
    how: 'You are Relish, guiding Rusty down the glowing path. Swipe or tap left and right to steer around anything in the way. Pick up the treats.',
    road: { vp: [0.40, 0.47], near: [0.52, 0.72, 0.42], depth: 6, color: '#fff2a0', opacity: 0.12, line: '#fff6b0' },
    player: '\u{1F415}‍\u{1F9BA}', color: '#ffe066',
    obstacles: [{ e: '\u{1F6A7}', name: 'Roadwork' }, { e: '\u{1F43F}️', name: 'A squirrel' }, { e: '\u{1F6F4}', name: 'A scooter in the way' }, { e: '\u{1F333}', name: 'A low branch' }],
    pickups: [{ e: '\u{1F9B4}', name: 'treat' }, { e: '\u{1F49B}', name: 'good dog' }], pickName: 'treats',
    healTitle: 'Good dog!', healSay: 'Good dog! One bump forgiven.',
    time: 58, travel: [3.0, 2.0], every: [1.55, 1.0], double: [0.05, 0.3], pickChance: 0.6, healEvery: 5,
    sound: { obs: [220, 'square'], pick: [1318, 'sine'], beat: [240, 'triangle', 0.035] },
    win: { title: 'Home together', line: '“You build a relationship, you know? You learn to work together.” — Rusty Perez' },
    lose: { title: 'Take a breath, try again', line: '“I get to take an amazing dog with me everywhere I go.” — Rusty Perez' },
  },
  'pedals-of-freedom': {
    engine: 'runner', title: 'Five-block ride', kicker: 'Five-block ride', unit: 'blocks', goal: 5,
    how: 'Ride your bike down the sidewalk. Swipe or tap left and right to miss the bumps, and ring the bells as you pass.',
    road: { vp: [0.31, 0.47], near: [0.5, 0.72, 0.46], depth: 5, color: '#3a2a10', opacity: 0.2, line: '#4a2a10' },
    player: '\u{1F6B2}', color: '#ffd25a',
    obstacles: [{ e: '\u{1F573}️', name: 'A bump in the sidewalk' }, { e: '\u{1F408}', name: 'A cat' }, { e: '\u{1F5D1}️', name: 'A trash can' }, { e: '\u{1FAA8}', name: 'A cracked slab' }],
    pickups: [{ e: '\u{1F514}', name: 'bell' }, { e: '\u{1F31E}', name: 'sunshine' }], pickName: 'bells',
    healTitle: 'Back in balance', healSay: 'Back in balance. One wobble forgiven.',
    time: 56, travel: [2.7, 1.7], every: [1.4, 0.85], double: [0.08, 0.4], pickChance: 0.55, healEvery: 6,
    sound: { obs: [180, 'square'], pick: [1568, 'triangle'], beat: [330, 'sine', 0.03] },
    win: { title: 'Free on two wheels', line: '“I knew every bump in the sidewalk within a five-block radius.” — Bill McCann' },
    lose: { title: 'Back on the bike', line: '“…somehow I learned to balance and ride.” — Bill McCann' },
  },
  'joyride': {
    engine: 'runner', title: 'Sunset joyride', kicker: 'Sunset joyride', unit: 'miles', goal: 10,
    how: 'Cruise down the palm boulevard with your mom. Swipe or tap left and right to change lanes, dodge the cones and potholes, and catch the songs.',
    road: { vp: [0.5, 0.49], near: [0.5, 0.72, 0.46], depth: 7, color: '#2a0f18', opacity: 0.18, line: '#ffe2b8' },
    player: '\u{1F697}', color: '#ffb36b', hitColor: '#ff4d6d',
    obstacles: [{ e: '\u{1F6A7}', name: 'Cones' }, { e: '\u{1F573}️', name: 'A pothole' }, { e: '\u{1F69A}', name: 'A slow truck' }],
    pickups: [{ e: '\u{1F3B5}', name: 'song' }, { e: '\u{1F3B6}', name: 'song' }, { e: '\u{1F366}', name: 'ice cream stop' }], pickName: 'songs',
    healTitle: 'Windows down', healSay: 'Windows down, singing loud. One bump forgiven.',
    time: 60, travel: [2.8, 1.8], every: [1.35, 0.85], double: [0.08, 0.4], pickChance: 0.6, healEvery: 6,
    sound: { obs: [233, 'sawtooth'], pick: [1175, 'sine'], beat: [98, 'triangle', 0.045] },
    win: { title: 'What a ride', line: '“We like to just drive around together sometimes.” — Shardasia Hadley' },
    lose: { title: 'Pull over, go again', line: '“She tries to see the world through my perspective, and I really do appreciate that.” — Shardasia Hadley' },
  },
  'roller-coaster-of-emotions': {
    engine: 'runner', title: 'Ride the emotions', kicker: 'Ride the emotions', unit: 'feet of track', goal: 600,
    how: 'Ride the coaster over the city. Swipe or tap left and right to catch the good feelings and dodge fear, doubt and sadness. Hold on, the speed rises and falls.',
    road: { vp: [0.5, 0.34], near: [0.5, 0.72, 0.5], depth: 5, color: '#ff7a1a', opacity: 0.22, line: '#ffc24a' },
    player: '\u{1F3A2}', color: '#7dffb0', hitColor: '#8a7dff',
    obstacles: [{ e: '\u{1F628}', name: 'Fear' }, { e: '\u{1F622}', name: 'Sadness' }, { e: '\u{1F914}', name: 'Doubt' }, { e: '\u{1F620}', name: 'Anger' }],
    pickups: [{ e: '\u{1F604}', name: 'joy' }, { e: '\u{1F4AA}', name: 'courage' }, { e: '\u{1F496}', name: 'love' }, { e: '\u{1F31F}', name: 'hope' }], pickName: 'good feelings',
    hitTitle: 'That one hurt', healTitle: 'You are still you', healSay: 'Good feelings lift you back up.',
    time: 56, travel: [2.6, 1.5], every: [1.3, 0.8], double: [0.12, 0.45], pickChance: 0.65, healEvery: 5, wave: 0.25,
    sound: { obs: [147, 'sawtooth'], pick: [1397, 'triangle'], beat: [70, 'square', 0.03] },
    win: { title: 'You rode it out', line: '“I felt stuck on this roller coaster of different emotions throughout that year.” — Alayna Lopez' },
    lose: { title: 'Climb back on', line: '“I had to throw away who I was because of this incorrect perception of what a blind person was…” — Alayna Lopez' },
  },
  'back-of-a-harley': {
    engine: 'runner', title: 'Open road', kicker: 'Open road', unit: 'miles', goal: 60,
    how: 'Ride the Harley down the open highway, into the sun. Swipe or tap left and right to change lanes around trucks and potholes, and soak up the sunbeams.',
    road: { vp: [0.72, 0.36], near: [0.56, 0.72, 0.5], depth: 6, color: '#24242a', opacity: 0.6, line: '#ffd34d' },
    player: '\u{1F3CD}️', color: '#ffcf6b',
    obstacles: [{ e: '\u{1F69B}', name: 'A big rig' }, { e: '\u{1F573}️', name: 'A pothole' }, { e: '\u{1F98C}', name: 'A deer' }, { e: '\u{1FAA8}', name: 'A rock' }],
    pickups: [{ e: '☀️', name: 'sunbeam' }, { e: '\u{1F985}', name: 'eagle overhead' }], pickName: 'sunbeams',
    healTitle: 'Sun on your face', healSay: 'Sun on your face. One scrape forgiven.',
    time: 52, travel: [2.3, 1.45], every: [1.25, 0.8], double: [0.1, 0.45], pickChance: 0.5, healEvery: 6,
    sound: { obs: [196, 'square'], pick: [1046, 'triangle'], beat: [55, 'sawtooth', 0.06] },
    win: { title: 'In your blood', line: '“I’ve seen a whole lot of this country on the back of a Harley.” — Craig Ellis' },
    lose: { title: 'Kickstand down', line: '“It’s one of those hobbies that gets in your blood.” — Craig Ellis' },
  },
  'pathways-unveiled': {
    engine: 'runner', title: 'Roads keep opening', kicker: 'Roads keep opening', unit: 'miles', goal: 30,
    how: 'Two sisters drive the winding roads together. Swipe or tap left and right to steer past the dead ends, and gather the colours of hope.',
    road: { vp: [0.52, 0.22], near: [0.42, 0.72, 0.38], depth: 2.4, color: '#0a0d1c', opacity: 0.3, line: '#ffffff' },
    player: '\u{1F46D}', color: '#ffd23f', hitColor: '#ff3b3b',
    obstacles: [{ e: '⛔', name: 'A dead end' }, { e: '\u{1F6A7}', name: 'Road closed' }, { e: '\u{1F32B}️', name: 'Fog' }],
    pickups: [{ e: '\u{1F49B}', name: 'joy' }, { e: '\u{1F499}', name: 'strength' }, { e: '❤️', name: 'love' }, { e: '\u{1F91D}', name: 'support' }], pickName: 'colours of hope',
    hitTitle: 'Dead end', healTitle: 'Sisters lean in', healSay: 'You lean on each other. One dead end forgiven.',
    time: 58, travel: [2.9, 1.9], every: [1.45, 0.9], double: [0.08, 0.4], pickChance: 0.6, healEvery: 5,
    sound: { obs: [208, 'square'], pick: [1245, 'sine'], beat: [130, 'triangle', 0.035] },
    win: { title: 'New roads open', line: '“The roads and the avenues continue to open and spread…” — April & Melissa' },
    lose: { title: 'Another road begins', line: '“…it gives us an ability to share and hopefully help someone else that’s newly diagnosed.” — April & Melissa' },
  },
};
